name: moor_shared
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dart
  cupertino_icons: ^0.1.2
  moor: ^3.1.0
  rxdart: ^0.22.2
  intl: ^0.16.0

  # Also use the latest version.
  sqlite3_flutter_libs: ^0.2.0

  # Helper to find the database path on mobile
  path_provider: ^1.3.0
  path: ^1.6.4
  undo: ^1.3.0+1
  
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5

dev_dependencies:
  moor_generator: ^3.1.0
  build_runner: ^1.6.7
  build_web_compilers: ^2.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
